apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giro
  name: giro
spec:
  containers:
    - image: nginx
      name: webserver
      # Lista de montagens de volume.
      volumeMounts:
        - mountPath: /vps62951
          name: primeiro-volume # <-- CORREÇÃO: Nome em minúsculas
      # O campo args pode ser omitido se não for necessário, ou vazio (null)
      # Se você quiser passar argumentos, ficaria assim:
      # args:
      #   - "/bin/sh"
      #   - "-c"
      #   - "sleep 3600"
      args: [] # Deixando vazio para garantir a estrutura
      resources:
        limits:
          cpu: "1"
          memory: "128Mi"
        requests:
          cpu: "0.3"
          memory: "64Mi"
  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  
  volumes:
    - name: primeiro-volume # <-- CORREÇÃO: Nome em minúsculas
      emptyDir:
        sizeLimit: 236Mi
