apiVersion: v1
kind: Pod
metadata:
  labels:
    run: teste
  name: teste
spec:
  containers:
  - image: nginx
    name: teste
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
